@php($formProduct = $product ?? null)
@php($formVariants = old('variants', $formProduct?->variants->map(fn ($variant) => ['id' => $variant->id, 'label' => $variant->label, 'price_adjustment' => $variant->price_adjustment, 'is_active' => $variant->is_active, 'is_quantity_based' => $variant->is_quantity_based])->values()->all() ?? []))
@php($formIngredients = old('ingredients', $formProduct?->ingredients->map(fn ($ingredient) => ['ingredient_id' => $ingredient->ingredient_id, 'product_variant_id' => $ingredient->product_variant_id, 'quantity_needed' => $ingredient->quantity_needed, 'ratio_per_unit' => $ingredient->ratio_per_unit])->values()->all() ?? []))
<div x-data="productForm(@js($formVariants), @js($formIngredients))" class="space-y-6"><div class="flex gap-2 overflow-x-auto border-b border-stone-200 pb-3"><template x-for="tab in [['info', 'Info dasar'], ['variants', 'Varian'], ['ingredients', 'Resep / Bahan'], ['gallery', 'Galeri foto']]" :key="tab[0]"><button type="button" @click="section = tab[0]" :class="section === tab[0] ? 'bg-rose-50 text-rose-600' : 'text-stone-500'" class="whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold" x-text="tab[1]"></button></template></div>
    <x-card x-show="section === 'info'" x-cloak>
        <div class="grid gap-5 sm:grid-cols-2">
            <div class="sm:col-span-2">
                <label for="name" class="text-sm font-semibold text-stone-700">Nama produk</label>
                <input id="name" name="name" value="{{ old('name', $formProduct?->name) }}" required class="mt-2 h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">
                <p class="mt-1.5 text-xs text-stone-400">Slug dibuat otomatis dari nama produk.</p>
                @error('name')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror
            </div>
            <div><label for="category_id" class="text-sm font-semibold text-stone-700">Kategori</label><select id="category_id" name="category_id" required class="mt-2 h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $formProduct?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
            <div><label for="base_price" class="text-sm font-semibold text-stone-700">Harga dasar</label><input id="base_price" name="base_price" type="number" min="0" step="1000" value="{{ old('base_price', $formProduct?->base_price) }}" required class="mt-2 h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">@error('base_price')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
            <div class="sm:col-span-2"><label for="description" class="text-sm font-semibold text-stone-700">Deskripsi</label><textarea id="description" name="description" rows="5" class="mt-2 w-full rounded-xl border-stone-200 bg-white px-4 py-3 text-sm focus:border-rose-300 focus:ring-rose-200">{{ old('description', $formProduct?->description) }}</textarea></div>
            <label class="flex items-center gap-3 rounded-xl border border-stone-100 bg-stone-50 p-4"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $formProduct?->is_active ?? true)) class="h-4 w-4 rounded border-stone-300 text-rose-500"><span class="text-sm font-semibold text-stone-700">Produk aktif</span></label>
            <label class="flex items-center gap-3 rounded-xl border border-stone-100 bg-stone-50 p-4"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $formProduct?->is_featured ?? false)) class="h-4 w-4 rounded border-stone-300 text-rose-500"><span class="text-sm font-semibold text-stone-700">Produk unggulan</span></label>
            <label class="flex items-center gap-3 rounded-xl border border-stone-100 bg-stone-50 p-4 sm:col-span-2"><input type="hidden" name="allow_multiple_variants" value="0"><input type="checkbox" name="allow_multiple_variants" value="1" @checked(old('allow_multiple_variants', $formProduct?->allow_multiple_variants ?? false)) class="h-4 w-4 rounded border-stone-300 text-rose-500"><span class="text-sm font-semibold text-stone-700">Izinkan pilih banyak varian sekaligus</span></label>
        </div>
    </x-card>
    <x-card x-show="section === 'variants'" x-cloak>
        <div class="flex items-center justify-between gap-4">
            <div><h2 class="font-serif text-xl font-semibold text-stone-800">Varian buket</h2><p class="mt-1 text-sm text-stone-500">SKU dibuat otomatis dari nama produk dan label varian. Aktifkan “Pakai jumlah” agar pelanggan dapat menentukan qty.</p></div>
            <button type="button" @click="addVariant" class="h-10 shrink-0 rounded-xl bg-rose-50 px-4 text-sm font-semibold text-rose-600">+ Varian</button>
        </div>
        <div class="mt-5 space-y-3">
            <template x-for="(variant, index) in variants" :key="index">
                <div class="grid gap-3 rounded-xl border border-stone-100 bg-stone-50 p-4 sm:grid-cols-[minmax(0,1fr)_10rem_auto]">
                    <input type="hidden" :name="`variants[${index}][id]`" x-model="variant.id">
                    <div><label class="text-xs font-semibold text-stone-500">Label</label><input :name="`variants[${index}][label]`" x-model="variant.label" class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm" placeholder="Medium"></div>
                    <div><label class="text-xs font-semibold text-stone-500">Penyesuaian</label><input :name="`variants[${index}][price_adjustment]`" x-model="variant.price_adjustment" type="number" step="1000" class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm"></div>
                    <div class="flex items-end gap-2"><div class="mb-2 flex flex-col gap-1 text-xs text-stone-500"><label><input type="hidden" :name="`variants[${index}][is_active]`" value="0"><input :name="`variants[${index}][is_active]`" x-model="variant.is_active" value="1" type="checkbox" class="h-4 w-4 rounded border-stone-300 text-rose-500"> Aktif</label><label><input type="hidden" :name="`variants[${index}][is_quantity_based]`" value="0"><input :name="`variants[${index}][is_quantity_based]`" x-model="variant.is_quantity_based" value="1" type="checkbox" class="h-4 w-4 rounded border-stone-300 text-rose-500"> Pakai jumlah</label></div><button type="button" @click="variants.splice(index, 1)" class="mb-1 rounded-lg p-2 text-rose-500 hover:bg-rose-100" aria-label="Hapus varian">×</button></div>
                </div>
            </template>
            <p x-show="variants.length === 0" class="rounded-xl border border-dashed border-stone-200 px-4 py-6 text-center text-sm text-stone-400">Belum ada varian. Produk tetap dapat dijual dengan harga dasar.</p>
        </div>
    </x-card>
    <x-card x-show="section === 'ingredients'" x-cloak>
        <div class="flex items-center justify-between gap-4"><div><h2 class="font-serif text-xl font-semibold text-stone-800">Resep / bahan</h2><p class="mt-1 text-sm text-stone-500">Tentukan kebutuhan bahan tetap per buket atau rasio untuk varian berbasis qty.</p></div><button type="button" @click="addRecipe" class="h-10 shrink-0 rounded-xl bg-rose-50 px-4 text-sm font-semibold text-rose-600">+ Bahan</button></div>
        @if($errors->has('ingredients.*'))<p class="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-600">Periksa kembali nilai resep atau bahan yang ditandai.</p>@endif
        <div class="mt-5 space-y-3">
            <template x-for="(recipe, index) in recipes" :key="index">
                <div class="grid gap-3 rounded-xl border border-stone-100 bg-stone-50 p-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,12rem)_auto]">
                    <div><label class="text-xs font-semibold text-stone-500">Bahan</label><select :name="`ingredients[${index}][ingredient_id]`" x-model="recipe.ingredient_id" required class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm"><option value="">Pilih bahan</option>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}">{{ $ingredient->name }} ({{ $ingredient->unit }})</option>@endforeach</select></div>
                    <div><label class="text-xs font-semibold text-stone-500">Varian</label><select :name="`ingredients[${index}][product_variant_id]`" x-model="recipe.product_variant_id" class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm"><option value="">Resep default</option><template x-for="variant in persistedVariants()" :key="variant.id"><option :value="variant.id" x-text="variant.label"></option></template></select></div>
                    <div>
                        <label class="text-xs font-semibold text-stone-500" x-text="isQuantityBasedRecipe(recipe) ? 'Rasio' : 'Qty per buket'"></label>
                        <input x-show="! isQuantityBasedRecipe(recipe)" :name="! isQuantityBasedRecipe(recipe) ? `ingredients[${index}][quantity_needed]` : null" x-model="recipe.quantity_needed" :required="! isQuantityBasedRecipe(recipe)" type="number" min="0.001" step="0.001" class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm" placeholder="Jumlah">
                        <input x-show="isQuantityBasedRecipe(recipe)" :name="isQuantityBasedRecipe(recipe) ? `ingredients[${index}][ratio_per_unit]` : null" x-model="recipe.ratio_per_unit" :required="isQuantityBasedRecipe(recipe)" type="number" min="0.001" step="0.001" class="mt-1 h-11 w-full rounded-lg border-stone-200 bg-white px-3 text-sm" placeholder="1">
                        <p x-show="isQuantityBasedRecipe(recipe)" class="mt-1.5 text-xs leading-5 text-stone-400">Jumlah aktual dihitung dari qty yang dipilih customer saat checkout × rasio ini</p>
                    </div>
                    <button type="button" @click="recipes.splice(index, 1)" class="rounded-lg px-3 text-rose-500 hover:bg-rose-100" aria-label="Hapus bahan">×</button>
                </div>
            </template>
            <p x-show="recipes.length === 0" class="rounded-xl border border-dashed border-stone-200 px-4 py-6 text-center text-sm text-stone-400">Belum ada bahan. Tambahkan resep agar stok berkurang otomatis saat pesanan diproses.</p>
        </div>
    </x-card>
    <x-card x-show="section === 'gallery'" x-cloak><h2 class="font-serif text-xl font-semibold text-stone-800">Galeri foto</h2><p class="mt-1 text-sm text-stone-500">JPG, PNG, atau WebP maksimal 2MB per foto. Pada edit produk, unggahan foto baru akan menggantikan seluruh galeri lama.</p><input type="file" name="images[]" multiple accept=".jpg,.jpeg,.png,.webp" class="mt-5 block w-full rounded-xl border border-dashed border-rose-200 bg-rose-50/50 px-4 py-4 text-sm text-stone-600">
        @error('images')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror
        @if($formProduct && $formProduct->images->isNotEmpty())<div class="mt-5 grid gap-3 sm:grid-cols-3" data-image-gallery>@foreach($formProduct->images as $image)<div data-image-card class="overflow-hidden rounded-xl border border-stone-100 bg-white"><img src="{{ Storage::url($image->path) }}" alt="{{ $formProduct->name }}" class="aspect-square w-full object-cover"><div class="flex items-center justify-between p-2"><label class="flex items-center gap-1.5 text-xs font-semibold text-stone-600"><input type="radio" name="primary_image_id" value="{{ $image->id }}" @checked(old('primary_image_id', $formProduct->primary_image?->id) == $image->id) class="h-3.5 w-3.5 border-stone-300 text-rose-500">Utama</label><input type="hidden" name="image_order[]" value="{{ $image->id }}"><div class="flex items-center gap-1"><button type="button" onclick="const card=this.closest('[data-image-card]'); const previous=card.previousElementSibling; if (previous) card.parentElement.insertBefore(card, previous)" class="rounded p-1 text-stone-400 hover:bg-stone-100" aria-label="Naikkan urutan foto">↑</button><button type="button" onclick="const card=this.closest('[data-image-card]'); const next=card.nextElementSibling; if (next) card.parentElement.insertBefore(next, card)" class="rounded p-1 text-stone-400 hover:bg-stone-100" aria-label="Turunkan urutan foto">↓</button><button type="submit" form="delete-image-{{ $image->id }}" class="text-xs font-semibold text-rose-600">Hapus</button></div></div></div>@endforeach</div>@endif</x-card>
    <div class="flex justify-end gap-3"><a href="{{ route('admin.products.index') }}" class="inline-flex h-11 items-center rounded-xl px-5 text-sm font-semibold text-stone-500">Batal</a><button type="submit" class="h-11 rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white shadow-sm hover:bg-rose-600">{{ $submitLabel }}</button></div>
</div>
