<?php

return [
    'catalog' => [
        'title' => 'Bouquet Collection | Suki Craft', 'description' => 'Discover Suki Craft bouquets for every special occasion.', 'eyebrow' => 'Suki Craft Collection', 'heading' => 'Flowers for every message you want to share.', 'intro' => 'Discover floral arrangements made for little celebrations, special days, and every feeling in between.', 'search_label' => 'Search bouquets', 'search_placeholder' => 'Search bouquets, occasions, or flower types...', 'search' => 'Search', 'category_label' => 'Bouquet categories', 'all' => 'All bouquets', 'custom_eyebrow' => 'Have an idea of your own?', 'custom_description' => 'Create a bouquet around the occasion, flowers, and budget you have in mind.', 'custom_action' => 'Request a custom bouquet', 'featured' => 'Picked for you', 'search_results' => 'Search results', 'all_collections' => 'All collections', 'found' => 'bouquets found',
    ],
    'checkout' => [
        'title' => 'Checkout | Suki Craft', 'back_to_cart' => 'Back to cart', 'eyebrow' => 'Just one more step', 'heading' => 'Arrange your bouquet delivery', 'delivery_data' => 'Delivery details', 'confirmation' => 'Confirmation', 'recipient_title' => 'Bouquet recipient', 'recipient_intro' => 'We use these details to arrange your delivery.', 'recipient_name' => 'Recipient name', 'recipient_name_placeholder' => 'Recipient’s full name', 'whatsapp' => 'WhatsApp number', 'phone_hint' => 'Use the format 08xx or +628xx.', 'optional' => 'optional', 'email_placeholder' => 'email@example.com', 'delivery_title' => 'Delivery schedule', 'delivery_intro' => 'Choose the date and time that work best for the recipient.', 'delivery_date' => 'Delivery date', 'delivery_date_hint' => 'Orders can be delivered from today, subject to time-slot availability.', 'arrival_time' => 'Estimated arrival time', 'choose_delivery_time' => 'Choose a delivery time', 'delivery_address' => 'Full delivery address', 'address_placeholder' => 'Street name, house number, neighbourhood, district, and a helpful landmark', 'additional_notes' => 'Additional notes', 'notes_placeholder' => 'For example: Please contact the recipient before arriving.', 'order_eyebrow' => 'Your order', 'summary' => 'Order summary', 'close' => 'Close', 'view_bouquets' => 'View bouquets', 'custom_bouquet' => 'Custom Bouquet #:number', 'subtotal' => 'Bouquet subtotal', 'delivery_fee' => 'Delivery fee', 'promo_code' => 'Promo code', 'apply' => 'Apply', 'promo_applied' => 'Promo applied:', 'promo_discount' => 'Promo discount', 'total' => 'Total payment', 'total_after_discount' => 'Final total', 'total_before_discount' => 'Total before discount', 'total_formula' => 'Total = bouquet subtotal + delivery fee − promo discount.', 'submit' => 'Place order', 'payment_note' => 'Payment details will appear after your order is placed.', 'promo_failed' => 'Your promo code could not be applied. Please try again.', 'promo_network_failed' => 'Your promo code could not be applied. Reload the page and try again.', 'promo_no_longer_valid' => 'This promo is no longer valid.',
    ],
    'how_to_order' => [
        'title' => 'How to Order | Sukicraft.id', 'description' => 'A simple guide to ordering a Sukicraft.id bouquet, from choosing an arrangement to tracking delivery.', 'hero_eyebrow' => 'A simple way to shop', 'hero_heading' => 'From choosing a bouquet to reaching its recipient.', 'hero_intro' => 'Follow these six simple steps to create a thoughtful surprise. You can start browsing without creating an account.', 'browse' => 'Browse bouquets', 'track' => 'Track order', 'journey' => 'Your order journey',
        'summary_steps' => [['number' => '01', 'label' => 'Choose a bouquet'], ['number' => '02', 'label' => 'Add a personal touch'], ['number' => '03', 'label' => 'Review your cart'], ['number' => '04', 'label' => 'Arrange delivery'], ['number' => '05', 'label' => 'Pay and upload proof'], ['number' => '06', 'label' => 'Track it to delivery']],
        'steps_eyebrow' => 'Six simple steps', 'steps_heading' => 'One step at a time, until your surprise is on its way.', 'steps_intro' => 'Each stage is designed to make the next step clear.',
        'steps' => [['number' => '01', 'title' => 'Find the right bouquet', 'description' => 'Browse the catalogue and choose an arrangement that suits the occasion and the feeling you want to share.', 'action' => 'Browse collections', 'route' => 'products.index', 'icon' => '✿'], ['number' => '02', 'title' => 'Make it personal', 'description' => 'Choose an available variant, write a card message, add a note for the florist, then choose the bouquet quantity.', 'action' => null, 'route' => null, 'icon' => '♡'], ['number' => '03', 'title' => 'Save it to your cart', 'description' => 'Select the add-to-cart button. There, you can review your bouquet details, quantity, and order subtotal.', 'action' => 'Open cart', 'route' => 'cart.index', 'icon' => '⌑'], ['number' => '04', 'title' => 'Enter delivery details', 'description' => 'Continue to checkout to enter the recipient’s name, WhatsApp number, full address, delivery date, and time slot.', 'action' => 'View catalogue', 'route' => 'products.index', 'icon' => '⌖'], ['number' => '05', 'title' => 'Place your order and pay', 'description' => 'Once your order is placed, pay by QRIS or bank transfer, then upload your proof of payment for verification.', 'action' => null, 'route' => null, 'icon' => '✓'], ['number' => '06', 'title' => 'Follow your order', 'description' => 'Use Track Order to see status updates, from payment verification to bouquet delivery.', 'action' => 'Track order', 'route' => 'tracking.create', 'icon' => '⌁']],
        'before_checkout' => 'Before checkout', 'details_heading' => 'A few details make delivery feel just right.', 'details_intro' => 'The more complete your information, the easier it is for our team to prepare the arrangement and for the courier to deliver it.', 'details' => [['title' => 'Full address', 'description' => 'Include the house number, area, and a helpful landmark for the courier.'], ['title' => 'Active WhatsApp number', 'description' => 'Use a number we can reach if the courier needs confirmation.'], ['title' => 'Delivery schedule', 'description' => 'Choose a date and time slot that suits the recipient’s plans.'], ['title' => 'Card message and notes', 'description' => 'Check the spelling of your message and add any special requests.']],
        'faq_eyebrow' => 'Frequently asked questions', 'faq_heading' => 'What you need to know before ordering.', 'faqs' => [['question' => 'Do I need an account to place an order?', 'answer' => 'No. You can choose a bouquet, enter recipient details, and place an order as a guest. A customer account is useful when you want to manage your profile and order history.'], ['question' => 'When do I pay for my order?', 'answer' => 'Payment is made after you place your order. The confirmation page shows QRIS or bank-transfer information, where you can also upload proof of payment.'], ['question' => 'How can I check my order status?', 'answer' => 'Open Track Order to see your order progress after payment is confirmed and delivery is scheduled.']],
        'cta_eyebrow' => 'Ready to create a surprise?', 'cta_heading' => 'Choose a bouquet that tells your story.', 'cta_action' => 'Browse bouquet collections',
    ],
];
