@extends('layouts.store')

@section('title', 'Profil Saya | Suki Craft')

@section('content')
    <section class="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
        <div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rose-500">Akun Suki Craft</p><h1 class="mt-2 font-serif text-3xl font-semibold tracking-tight text-stone-800">Profil & keamanan</h1><p class="mt-2 text-sm text-stone-500">Kelola informasi akun dan password Anda.</p></div>
        <div class="mt-6"><x-customer.account-navigation active="profile" /></div>
        @if(session('success'))<div class="mt-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
        <div class="mt-6 grid gap-6 lg:grid-cols-2">
            <section class="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="font-serif text-2xl font-semibold text-stone-800">Informasi profil</h2><p class="mt-1 text-sm text-stone-500">Data ini akan mengisi checkout secara otomatis, tetapi tetap bisa diubah per pesanan.</p><form method="POST" action="{{ route('customer.profile.update') }}" class="mt-6 space-y-5">@csrf @method('PUT')<div><label for="name" class="text-sm font-semibold text-stone-700">Nama lengkap</label><input id="name" name="name" type="text" value="{{ old('name', $customer->name) }}" required autocomplete="name" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200 @error('name') border-rose-400 @enderror">@error('name')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="email" class="text-sm font-semibold text-stone-700">Email</label><input id="email" name="email" type="email" value="{{ old('email', $customer->email) }}" required autocomplete="email" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200 @error('email') border-rose-400 @enderror">@error('email')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="phone" class="text-sm font-semibold text-stone-700">Nomor WhatsApp</label><input id="phone" name="phone" type="tel" value="{{ old('phone', $customer->phone) }}" required inputmode="tel" autocomplete="tel" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200 @error('phone') border-rose-400 @enderror">@error('phone')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><button type="submit" class="h-12 rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white transition hover:bg-rose-600">Simpan perubahan</button></form></section>
            <section class="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><h2 class="font-serif text-2xl font-semibold text-stone-800">Ganti password</h2><p class="mt-1 text-sm text-stone-500">Masukkan password lama untuk mengonfirmasi perubahan.</p><form method="POST" action="{{ route('customer.profile.password.update') }}" class="mt-6 space-y-5">@csrf @method('PUT')<div><label for="current_password" class="text-sm font-semibold text-stone-700">Password saat ini</label><input id="current_password" name="current_password" type="password" required autocomplete="current-password" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200 @error('current_password') border-rose-400 @enderror">@error('current_password')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="password" class="text-sm font-semibold text-stone-700">Password baru</label><input id="password" name="password" type="password" required autocomplete="new-password" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200 @error('password') border-rose-400 @enderror">@error('password')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="password_confirmation" class="text-sm font-semibold text-stone-700">Konfirmasi password baru</label><input id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm focus:border-rose-300 focus:ring-rose-200"></div><button type="submit" class="h-12 rounded-xl border border-rose-200 bg-rose-50 px-5 text-sm font-semibold text-rose-700 transition hover:bg-rose-100">Perbarui password</button></form></section>
        </div>
    </section>
@endsection
