@php($items = $cart?->itemGroups ?? collect())

<section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
    <div class="flex items-end justify-between gap-4 border-b border-stone-200 pb-6"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-rose-500">Your order</p><h1 class="mt-2 font-serif text-4xl font-semibold tracking-tight text-stone-800">Shopping cart</h1></div><a href="{{ route('products.index') }}" class="hidden text-sm font-semibold text-rose-600 hover:text-rose-700 sm:inline">Add another bouquet</a></div>
    @if (session('success'))<div class="mt-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('success') }}</div>@endif
    @if (session('error'))<div class="mt-6 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">{{ session('error') }}</div>@endif
    @if ($items->isEmpty())
        <div class="mt-8 rounded-3xl border border-dashed border-rose-200 bg-rose-50/60 px-6 py-16 text-center"><div class="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-2xl text-rose-400 shadow-sm">✿</div><h2 class="mt-5 font-serif text-2xl font-semibold text-stone-800">Your cart is empty</h2><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500">Browse our fresh flower collection and find a bouquet for your special moment.</p><a href="{{ route('products.index') }}" class="mt-6 inline-flex rounded-full bg-rose-500 px-5 py-3 text-sm font-semibold text-white transition hover:bg-rose-600">Browse bouquet collections</a></div>
    @else
        <div class="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_22rem] lg:items-start"><div class="space-y-4">@foreach ($items as $item)
            @php($imagePath = $item->product->primary_image?->path ?? $item->product->image)
            <article class="rounded-2xl border border-stone-200 bg-white p-4 sm:p-5"><div class="flex gap-4 sm:gap-5"><a href="{{ route('products.show', $item->product->slug) }}" class="h-24 w-20 shrink-0 overflow-hidden rounded-xl bg-rose-50 sm:h-28 sm:w-24">@if ($imagePath)<img src="{{ Storage::url($imagePath) }}" alt="{{ $item->product->name }}" class="h-full w-full object-cover">@else<div class="grid h-full place-items-center text-2xl text-rose-300">✿</div>@endif</a><div class="min-w-0 flex-1"><div class="flex gap-3"><div class="min-w-0 flex-1"><p class="text-xs font-semibold uppercase tracking-[0.13em] text-rose-500">{{ $item->product->category->name }}</p><h2 class="mt-1 truncate font-serif text-xl font-semibold text-stone-800">{{ $item->custom_request_id ? 'Custom Bouquet #'.($item->customRequest?->request_number ?? '') : $item->product->name }}<x-bouquet-size-label :item="$item" /></h2><x-order-item-price-breakdown :item="$item" /></div><form method="POST" action="{{ route('cart.remove', $item->id) }}" data-confirm="This bouquet will be removed from your cart." data-confirm-button="Yes, remove it" data-confirm-title="Remove this bouquet?">@csrf @method('DELETE')<button class="grid h-9 w-9 place-items-center rounded-full text-stone-400 transition hover:bg-rose-50 hover:text-rose-600" aria-label="Remove {{ $item->product->name }}"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="m6 7 .75 12h10.5L18 7M9.5 10.5v5m5-5v5M9 7V4.5h6V7M4.5 7h15" /></svg></button></form></div>
                @if ($item->card_message || $item->special_note)<div class="mt-3 space-y-1 rounded-xl bg-stone-50 px-3 py-2 text-xs leading-5 text-stone-500">@if ($item->card_message)<p><span class="font-semibold text-stone-600">Card:</span> {{ $item->card_message }}</p>@endif @if ($item->special_note)<p><span class="font-semibold text-stone-600">Note:</span> {{ $item->special_note }}</p>@endif</div>@endif
                <div class="mt-4 flex justify-end">@if ($item->custom_request_id)<p class="rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">1 bouquet · quantity quoted to order</p>@else<div class="flex items-center rounded-xl border border-stone-200"><form method="POST" action="{{ route('cart.update', $item->id) }}">@csrf @method('PATCH')<input type="hidden" name="quantity" value="{{ max(1, $item->bundle_quantity - 1) }}"><button class="grid h-9 w-9 place-items-center text-lg text-stone-500 transition hover:text-rose-600 disabled:opacity-30" @disabled($item->bundle_quantity === 1) aria-label="Decrease quantity">−</button></form><span class="w-8 text-center text-sm font-semibold text-stone-800">{{ $item->bundle_quantity }}</span><form method="POST" action="{{ route('cart.update', $item->id) }}">@csrf @method('PATCH')<input type="hidden" name="quantity" value="{{ min(99, $item->bundle_quantity + 1) }}"><button class="grid h-9 w-9 place-items-center text-lg text-stone-500 transition hover:text-rose-600" aria-label="Increase quantity">+</button></form></div>@endif</div></div></div></article>
        @endforeach<a href="{{ route('products.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-rose-600 hover:text-rose-700"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="m19 12H5m5-5-5 5 5 5" /></svg>Add another bouquet</a></div>
        <aside data-cart-summary class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm lg:sticky lg:top-24 lg:shadow-xl lg:shadow-stone-900/5"><h2 class="font-serif text-2xl font-semibold text-stone-800">Order summary</h2><dl class="mt-5 space-y-3 text-sm"><div class="flex items-center justify-between gap-4 border-b border-stone-100 pb-4 text-stone-600"><dt>Bouquet subtotal ({{ $items->sum('bundle_quantity') }} bouquets)</dt><dd class="font-semibold text-stone-800">Rp{{ number_format($total, 0, ',', '.') }}</dd></div><div class="text-xs leading-5 text-stone-500">Each bouquet breakdown includes the arrangement service and selected variant prices.</div></dl><p class="mt-4 text-xs leading-5 text-stone-500">Delivery starts at Rp{{ number_format((float) config('delivery.flat_fee', 0), 0, ',', '.') }} and is calculated from the route distance at checkout.</p><div class="mt-5 flex items-end justify-between border-t border-stone-100 pt-4"><span class="text-sm font-semibold text-stone-800">Estimated total</span><span class="font-serif text-2xl font-semibold text-stone-800">Rp{{ number_format($total, 0, ',', '.') }}</span></div><a href="{{ route('checkout.index') }}" class="mt-6 inline-flex h-12 w-full items-center justify-center rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-rose-600">Continue to checkout</a></aside></div>
    @endif
</section>
