@extends('layouts.admin')

@section('title', 'Dashboard')
@section('page-title', 'Dashboard')

@section('content')
    @php($maximumTrendRevenue = max(1, $trend->max('revenue')))
    @php($trendWidth = max(280, $trend->count() * 48))

    <div>
        <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
            <div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rose-500">Ringkasan toko</p><h1 class="mt-2 font-serif text-3xl font-semibold tracking-tight text-stone-800 sm:text-4xl">Selamat datang, {{ str(auth('admin')->user()->name)->before(' ') }} ✿</h1><p class="mt-2 text-sm text-stone-500">Pantau ritme toko dan semua momen spesial pelanggan hari ini.</p></div>
            <nav class="flex rounded-xl border border-stone-200 bg-white p-1 shadow-sm" aria-label="Pilih periode dashboard">
                @foreach(['today' => 'Hari ini', 'week' => 'Minggu ini', 'month' => 'Bulan ini'] as $value => $label)
                    <a href="{{ route('admin.dashboard', ['period' => $value]) }}" @class(['rounded-lg px-3 py-2 text-xs font-semibold transition sm:px-4 sm:text-sm', 'bg-rose-500 text-white shadow-sm' => $period === $value, 'text-stone-500 hover:bg-rose-50 hover:text-rose-600' => $period !== $value])>{{ $label }}</a>
                @endforeach
            </nav>
        </div>

        <div class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
            <x-stat-widget label="Pendapatan hari ini" :value="'Rp'.number_format($revenueToday, 0, ',', '.')" detail="Dari pesanan berstatus terbayar" tone="rose"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" d="M12 6v12m3-9.5c-.45-1.16-1.56-1.9-3-1.9-1.82 0-3.25 1.17-3.25 2.7 0 3.7 6.5 1.85 6.5 5.55 0 1.53-1.43 2.7-3.25 2.7-1.44 0-2.55-.74-3-1.9" /></svg></x-slot:icon></x-stat-widget>
            <x-stat-widget label="Pendapatan bulan ini" :value="'Rp'.number_format($revenueMonth, 0, ',', '.')" detail="Dari pesanan berstatus terbayar" tone="emerald"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.5h15M6.75 16.5V12m5.25 4.5V7.5m5.25 9V10.5" /></svg></x-slot:icon></x-stat-widget>
            <x-stat-widget label="Pesanan baru" :value="number_format($newOrderCount)" :detail="'Masuk pada '.$periodLabel" tone="sky"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M6.75 4.5h10.5v15h-10.5zM9 9h6m-6 3h6m-6 3h3" /></svg></x-slot:icon></x-stat-widget>
            <x-stat-widget label="Menunggu verifikasi" :value="number_format($awaitingVerificationCount)" detail="Perlu tindak lanjut admin" tone="amber"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="8.25" /><path stroke-linecap="round" d="M12 7.5V12l3 1.5" /></svg></x-slot:icon></x-stat-widget>
            <x-stat-widget label="Stok bahan menipis" :value="$lowStockIngredientCount" detail="Bahan yang perlu segera dipantau" tone="amber"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8.25v4.5m0 3v.01M4.5 19.5h15L12 4.5 4.5 19.5Z" /></svg></x-slot:icon></x-stat-widget>
        </div>

        <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(19rem,0.85fr)]">
            <x-card padding="p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-serif text-xl font-semibold text-stone-800">Tren penjualan</h2><p class="mt-1 text-sm text-stone-500">Pendapatan harian pada {{ strtolower($periodLabel) }}.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Rp{{ number_format($trend->sum('revenue'), 0, ',', '.') }}</span></div><div class="mt-7 overflow-x-auto"><svg class="h-56 min-w-full" viewBox="0 0 {{ $trendWidth }} 200" role="img" aria-label="Tren penjualan {{ strtolower($periodLabel) }}">@foreach($trend as $point) @php($height = max(3, (int) round(($point['revenue'] / $maximumTrendRevenue) * 130))) @php($x = $loop->index * 48 + 13) @php($y = 158 - $height)<title>{{ $point['label'] }}: Rp{{ number_format($point['revenue'], 0, ',', '.') }}</title><rect x="{{ $x }}" y="{{ $y }}" width="22" height="{{ $height }}" rx="5" fill="#fda4af" /><text x="{{ $x + 11 }}" y="182" text-anchor="middle" font-size="10" fill="#a8a29e">{{ $point['label'] }}</text>@endforeach<line x1="0" x2="{{ $trendWidth }}" y1="158" y2="158" stroke="#e7e5e4" /></svg></div></x-card>
            <x-card padding="p-5 sm:p-6"><h2 class="font-serif text-xl font-semibold text-stone-800">Status pesanan</h2><p class="mt-1 text-sm text-stone-500">Distribusi seluruh pesanan saat ini.</p><p class="mt-6 font-serif text-4xl font-semibold tracking-tight text-stone-800">{{ number_format($totalOrderCount) }}</p><p class="mt-1 text-xs text-stone-400">Total pesanan</p><div class="mt-6 space-y-3">@foreach($statusSummaries as $summary)<div class="flex items-center gap-3"><span @class(['h-2.5 w-2.5 rounded-full', 'bg-amber-300' => $summary['tone'] === 'amber', 'bg-sky-300' => $summary['tone'] === 'sky', 'bg-violet-300' => $summary['tone'] === 'violet', 'bg-emerald-300' => $summary['tone'] === 'emerald', 'bg-rose-300' => $summary['tone'] === 'rose'])></span><span class="text-sm text-stone-600">{{ $summary['label'] }}</span><span class="ml-auto text-sm font-semibold text-stone-800">{{ number_format($summary['value']) }}</span></div>@endforeach</div></x-card>
        </div>

        <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(19rem,0.85fr)]">
            <div class="min-w-0"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-serif text-xl font-semibold text-stone-800">Pesanan terbaru</h2><p class="mt-1 text-sm text-stone-500">Pesanan yang baru masuk ke toko.</p></div><a href="{{ route('admin.orders.index') }}" class="shrink-0 text-sm font-semibold text-rose-600 hover:text-rose-700">Lihat semua →</a></div><x-data-table :headers="['Pesanan', 'Pelanggan', 'Total', 'Status', 'Aksi']" :is-empty="$latestOrders->isEmpty()" empty-title="Belum ada pesanan masuk" empty-description="Pesanan dari pelanggan akan ditampilkan di sini.">@foreach($latestOrders as $order)<tr><td class="whitespace-nowrap px-5 py-4"><p class="font-mono text-xs font-bold text-stone-700">{{ $order->order_number }}</p><p class="mt-1 text-xs text-stone-400">{{ $order->created_at->locale('id')->translatedFormat('d M, H.i') }} WIB</p></td><td class="px-5 py-4"><p class="font-semibold text-stone-700">{{ $order->customer_name }}</p><p class="mt-0.5 text-xs text-stone-400">{{ $order->customer_phone }}</p></td><td class="whitespace-nowrap px-5 py-4 text-sm font-semibold text-stone-700">Rp{{ number_format($order->total, 0, ',', '.') }}</td><td class="whitespace-nowrap px-5 py-4"><x-status-badge :status="$order->status->label()" /></td><td class="whitespace-nowrap px-5 py-4"><a href="{{ route('admin.orders.show', $order) }}" class="rounded-lg px-3 py-2 text-xs font-semibold text-rose-600 transition hover:bg-rose-50">Lihat</a></td></tr>@endforeach</x-data-table></div>
            <div class="min-w-0"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-serif text-xl font-semibold text-stone-800">Bahan perlu perhatian</h2><p class="mt-1 text-sm text-stone-500">Bahan aktif yang berada di ambang minimum.</p></div><a href="{{ route('admin.ingredients.index') }}" class="shrink-0 text-sm font-semibold text-rose-600 hover:text-rose-700">Kelola →</a></div><x-card padding="p-2">@forelse($lowStockIngredients as $ingredient)<div class="flex items-center gap-3 rounded-xl p-3 hover:bg-rose-50/50"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-sm font-semibold text-amber-600">{{ str($ingredient->name)->substr(0, 1)->upper() }}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold text-stone-700">{{ $ingredient->name }}</p><p class="mt-0.5 text-xs text-stone-400">Ambang {{ number_format($ingredient->minimum_stock, 3, ',', '.') }} {{ $ingredient->unit }}</p></div><span class="text-xs font-semibold text-rose-600">{{ number_format($ingredient->current_stock, 3, ',', '.') }} {{ $ingredient->unit }}</span></div>@empty<x-empty-state title="Stok aman" description="Belum ada bahan yang berada di bawah ambang minimum." />@endforelse</x-card></div>
        </div>
    </div>
@endsection
