@extends('layouts.admin')

@section('title', 'Laporan & Keuangan')
@section('page-title', 'Laporan & Keuangan')

@section('content')
    @php($maxRevenue = max(1, $trend->max('revenue')))
    @php($trendWidth = max(400, $trend->count() * 56))
    <div class="flex flex-col justify-between gap-4 xl:flex-row xl:items-center"><div><h1 class="font-serif text-2xl font-semibold text-stone-800">Laporan penjualan</h1><p class="mt-1 text-sm text-stone-500">Ringkasan pendapatan dari pesanan dengan pembayaran yang telah dikonfirmasi.</p></div><button disabled title="Maatwebsite Excel belum terpasang" class="inline-flex h-11 items-center justify-center rounded-xl bg-stone-200 px-5 text-sm font-semibold text-stone-500">Export ke Excel · segera hadir</button></div>
    <x-card class="mt-6"><form method="GET" class="grid gap-4 lg:grid-cols-[auto_auto_auto_minmax(0,1fr)_minmax(0,1fr)_auto]"><select name="preset" class="h-11 rounded-xl border-stone-200 bg-white px-3 text-sm" onchange="this.form.submit()"><option value="today" @selected($filters['preset'] === 'today')>Hari ini</option><option value="week" @selected($filters['preset'] === 'week')>Minggu ini</option><option value="month" @selected($filters['preset'] === 'month')>Bulan ini</option><option value="last_month" @selected($filters['preset'] === 'last_month')>Bulan lalu</option><option value="custom" @selected($filters['preset'] === 'custom')>Rentang sendiri</option></select><select name="group_by" class="h-11 rounded-xl border-stone-200 bg-white px-3 text-sm"><option value="day" @selected($groupBy === 'day')>Harian</option><option value="week" @selected($groupBy === 'week')>Mingguan</option><option value="month" @selected($groupBy === 'month')>Bulanan</option></select><span class="hidden lg:block"></span><input name="from" type="date" value="{{ $filters['from'] }}" class="h-11 rounded-xl border-stone-200 bg-white px-3 text-sm"><input name="to" type="date" value="{{ $filters['to'] }}" class="h-11 rounded-xl border-stone-200 bg-white px-3 text-sm"><button class="h-11 rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white hover:bg-rose-600">Terapkan</button></form></x-card>
    <div class="mt-6 grid gap-4 md:grid-cols-3"><x-stat-widget label="Total pendapatan" :value="'Rp'.number_format($summary['revenue'], 0, ',', '.')" :detail="$filters['from'].' s.d. '.$filters['to']" tone="emerald"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m3-9.75a3 3 0 0 0-3-1.5c-1.66 0-3 .9-3 2.25s1.34 2.25 3 2.25 3 1.12 3 2.5S13.66 18.25 12 18.25A3.5 3.5 0 0 1 8.75 16.5" /></svg></x-slot:icon></x-stat-widget><x-stat-widget label="Total pesanan" :value="number_format($summary['orders'])" detail="Pesanan berstatus terkonfirmasi ke atas" tone="sky"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M6.75 5.25h10.5v13.5H6.75zM9 9h6m-6 3h6m-6 3h3" /></svg></x-slot:icon></x-stat-widget><x-stat-widget label="Rata-rata nilai pesanan" :value="'Rp'.number_format($summary['average_order'], 0, ',', '.')" detail="Nilai transaksi rata-rata" tone="violet"><x-slot:icon><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3.75v16.5m-4.5-12h9m-9 4.5h9m-9 4.5h9" /></svg></x-slot:icon></x-stat-widget></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(20rem,0.85fr)]"><x-card padding="p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-serif text-xl font-semibold text-stone-800">Tren penjualan</h2><p class="mt-1 text-sm text-stone-500">Pendapatan {{ $groupBy === 'day' ? 'harian' : ($groupBy === 'week' ? 'mingguan' : 'bulanan') }} pada periode terpilih.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Rp{{ number_format($summary['revenue'], 0, ',', '.') }}</span></div><div class="mt-7 overflow-x-auto"><svg class="h-56 min-w-full" viewBox="0 0 {{ $trendWidth }} 200" role="img" aria-label="Tren penjualan">@foreach($trend as $point) @php($height = max(3, (int) round(($point['revenue'] / $maxRevenue) * 130))) @php($x = $loop->index * 56 + 15) @php($y = 158 - $height)<title>{{ $point['label'] }}: Rp{{ number_format($point['revenue'], 0, ',', '.') }}</title><rect x="{{ $x }}" y="{{ $y }}" width="24" height="{{ $height }}" rx="5" fill="#fda4af" /><text x="{{ $x + 12 }}" y="182" text-anchor="middle" font-size="10" fill="#a8a29e">{{ $point['label'] }}</text>@endforeach<line x1="0" x2="{{ $trendWidth }}" y1="158" y2="158" stroke="#e7e5e4" /></svg></div></x-card><x-card padding="p-5 sm:p-6"><h2 class="font-serif text-xl font-semibold text-stone-800">Pendapatan kategori</h2><p class="mt-1 text-sm text-stone-500">Kontribusi per kategori buket.</p><div class="mt-6 space-y-4">@forelse($revenueByCategory as $category)<div><div class="flex justify-between gap-3 text-sm"><span class="truncate font-semibold text-stone-700">{{ $category->category_name }}</span><span class="whitespace-nowrap text-stone-500">Rp{{ number_format($category->revenue, 0, ',', '.') }}</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-stone-100"><div class="h-full rounded-full bg-rose-400" style="width: {{ $summary['revenue'] > 0 ? min(100, ($category->revenue / $summary['revenue']) * 100) : 0 }}%"></div></div></div>@empty<x-empty-state title="Belum ada pendapatan" description="Data kategori akan muncul setelah pesanan dikonfirmasi." />@endforelse</div></x-card></div>
    <div class="mt-6"><h2 class="mb-4 font-serif text-xl font-semibold text-stone-800">Produk terlaris</h2><x-data-table :headers="['Produk', 'Jumlah terjual', 'Pendapatan']" :is-empty="$topProducts->isEmpty()" empty-title="Belum ada transaksi" empty-description="Produk terlaris akan dihitung dari pesanan yang sudah dikonfirmasi.">@foreach($topProducts as $product)<tr><td class="px-5 py-4 font-semibold text-stone-700">{{ $product->product_name }}</td><td class="whitespace-nowrap px-5 py-4 text-sm text-stone-600">{{ number_format($product->quantity_sold) }} buket</td><td class="whitespace-nowrap px-5 py-4 text-sm font-semibold text-stone-700">Rp{{ number_format($product->revenue, 0, ',', '.') }}</td></tr>@endforeach</x-data-table></div>
@endsection
