@extends('layouts.admin')

@section('title', 'Stok Bahan')
@section('page-title', 'Stok Bahan')

@section('content')
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="font-serif text-2xl font-semibold text-stone-800">Stok bahan</h1><p class="mt-1 text-sm text-stone-500">Pantau bunga dan material yang digunakan pada setiap buket.</p></div><a href="{{ route('admin.ingredients.create') }}" class="inline-flex h-11 items-center justify-center rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white shadow-sm hover:bg-rose-600">+ Tambah bahan</a></div>
    <form method="GET" class="mt-6 flex gap-3"><input name="search" value="{{ $search }}" class="h-11 w-full max-w-md rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200" placeholder="Cari bahan..."><button class="h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-600 hover:border-rose-200">Cari</button></form>
    <div class="mt-6"><x-data-table :headers="['Bahan', 'Stok saat ini', 'Ambang', 'Status', 'Aksi']" :is-empty="$ingredients->isEmpty()" empty-title="Belum ada bahan" empty-description="Tambahkan bahan pertama untuk mulai mencatat persediaan.">@foreach($ingredients as $ingredient)<tr><td class="px-5 py-4"><p class="font-semibold text-stone-700">{{ $ingredient->name }}</p><p class="mt-1 text-xs text-stone-400">Satuan: {{ $ingredient->unit }}</p></td><td class="whitespace-nowrap px-5 py-4 text-sm font-semibold text-stone-700">{{ number_format($ingredient->current_stock, 3, ',', '.') }} {{ $ingredient->unit }}</td><td class="whitespace-nowrap px-5 py-4 text-sm text-stone-500">{{ number_format($ingredient->minimum_stock, 3, ',', '.') }}</td><td class="whitespace-nowrap px-5 py-4">@if(! $ingredient->is_active)<x-status-badge status="nonaktif" />@elseif($ingredient->current_stock <= $ingredient->minimum_stock)<span class="inline-flex rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700 ring-1 ring-inset ring-amber-100">Stok menipis</span>@else<x-status-badge status="aktif" />@endif</td><td class="whitespace-nowrap px-5 py-4"><div class="flex items-center gap-1"><a href="{{ route('admin.ingredients.show', $ingredient) }}" class="rounded-lg px-2 py-1.5 text-xs font-semibold text-rose-600 hover:bg-rose-50">Stok</a><a href="{{ route('admin.ingredients.edit', $ingredient) }}" class="rounded-lg px-2 py-1.5 text-xs font-semibold text-stone-600 hover:bg-stone-100">Edit</a><form method="POST" action="{{ route('admin.ingredients.toggle', $ingredient) }}">@csrf @method('PATCH')<button class="rounded-lg px-2 py-1.5 text-xs font-semibold text-stone-600 hover:bg-stone-100">{{ $ingredient->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></div></td></tr>@endforeach</x-data-table></div>
    <div class="mt-6">{{ $ingredients->links() }}</div>
@endsection
