@extends('layouts.admin')

@section('title', 'Pergerakan Stok')
@section('page-title', 'Pergerakan Stok')

@section('content')
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><a href="{{ route('admin.ingredients.index') }}" class="text-sm font-semibold text-rose-600 hover:text-rose-700">← Semua bahan</a><h1 class="mt-2 font-serif text-2xl font-semibold text-stone-800">{{ $ingredient->name }}</h1><p class="mt-1 text-sm text-stone-500">Stok saat ini: <span class="font-semibold text-stone-700">{{ number_format($ingredient->current_stock, 3, ',', '.') }} {{ $ingredient->unit }}</span> · Minimum {{ number_format($ingredient->minimum_stock, 3, ',', '.') }}</p></div><a href="{{ route('admin.ingredients.edit', $ingredient) }}" class="inline-flex h-11 items-center justify-center rounded-xl border border-stone-200 bg-white px-5 text-sm font-semibold text-stone-600 hover:border-rose-200">Edit bahan</a></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2"><x-card><h2 class="font-serif text-xl font-semibold text-stone-800">Stok masuk</h2><p class="mt-1 text-sm text-stone-500">Catat pembelian bahan baru.</p><form method="POST" action="{{ route('admin.ingredients.stock-in', $ingredient) }}" class="mt-5 space-y-4">@csrf<div><label class="text-sm font-semibold text-stone-700">Jumlah ({{ $ingredient->unit }})</label><input name="quantity" type="number" min="0.001" step="0.001" required class="mt-2 h-11 w-full rounded-xl border-stone-200 px-3 text-sm"><x-input-error :messages="$errors->get('quantity')" class="mt-2" /></div><div><label class="text-sm font-semibold text-stone-700">Alasan</label><input name="reason" required class="mt-2 h-11 w-full rounded-xl border-stone-200 px-3 text-sm" placeholder="Pembelian dari pemasok"><x-input-error :messages="$errors->get('reason')" class="mt-2" /></div><button class="h-11 rounded-xl bg-emerald-500 px-5 text-sm font-semibold text-white hover:bg-emerald-600">Catat stok masuk</button></form></x-card><x-card><h2 class="font-serif text-xl font-semibold text-stone-800">Penyesuaian stok</h2><p class="mt-1 text-sm text-stone-500">Gunakan setelah stok opname; boleh bernilai negatif.</p><form method="POST" action="{{ route('admin.ingredients.adjustment', $ingredient) }}" class="mt-5 space-y-4">@csrf<div><label class="text-sm font-semibold text-stone-700">Stok fisik baru ({{ $ingredient->unit }})</label><input name="quantity" type="number" step="0.001" required class="mt-2 h-11 w-full rounded-xl border-stone-200 px-3 text-sm"><x-input-error :messages="$errors->get('quantity')" class="mt-2" /></div><div><label class="text-sm font-semibold text-stone-700">Alasan</label><input name="reason" required class="mt-2 h-11 w-full rounded-xl border-stone-200 px-3 text-sm" placeholder="Stok opname"><x-input-error :messages="$errors->get('reason')" class="mt-2" /></div><button class="h-11 rounded-xl bg-amber-500 px-5 text-sm font-semibold text-white hover:bg-amber-600">Simpan penyesuaian</button></form></x-card></div>
    <div class="mt-6"><h2 class="mb-4 font-serif text-xl font-semibold text-stone-800">Riwayat pergerakan</h2><x-data-table :headers="['Tanggal', 'Tipe', 'Jumlah', 'Alasan', 'Pesanan']" :is-empty="$movements->isEmpty()" empty-title="Belum ada pergerakan" empty-description="Stok masuk, penyesuaian, dan pemakaian pesanan akan tampil di sini.">@foreach($movements as $movement)<tr><td class="whitespace-nowrap px-5 py-4 text-sm text-stone-600">{{ $movement->created_at->locale('id')->translatedFormat('d M Y, H.i') }}</td><td class="whitespace-nowrap px-5 py-4"><x-status-badge :status="match($movement->type) { 'in' => 'aktif', 'out' => 'dibatalkan', default => 'pending' }">{{ $movement->type === 'in' ? 'Masuk' : ($movement->type === 'out' ? 'Keluar' : 'Penyesuaian') }}</x-status-badge></td><td class="whitespace-nowrap px-5 py-4 text-sm font-semibold {{ $movement->quantity >= 0 ? 'text-emerald-600' : 'text-rose-600' }}">{{ $movement->quantity >= 0 ? '+' : '' }}{{ number_format($movement->quantity, 3, ',', '.') }}</td><td class="px-5 py-4 text-sm text-stone-600">{{ $movement->reason ?? '—' }}</td><td class="whitespace-nowrap px-5 py-4 text-sm text-stone-600">{{ $movement->order?->order_number ?? '—' }}</td></tr>@endforeach</x-data-table></div>
    <div class="mt-6">{{ $movements->links() }}</div>
@endsection
