<?php

return [
    'catalog' => [
        'title' => 'Koleksi Buket | Suki Craft',
        'description' => 'Temukan buket bunga pilihan dari Suki Craft untuk setiap momen istimewa.',
        'eyebrow' => 'Koleksi Suki Craft',
        'heading' => 'Buket untuk setiap pesan yang ingin disampaikan.',
        'intro' => 'Temukan rangkaian bunga yang dibuat untuk merayakan momen kecil, hari istimewa, dan segala rasa di antaranya.',
        'search_label' => 'Cari buket',
        'search_placeholder' => 'Cari buket, momen, atau jenis bunga...',
        'search' => 'Cari buket',
        'category_label' => 'Kategori buket',
        'all' => 'Semua buket',
        'custom_eyebrow' => 'Punya ide sendiri?',
        'custom_description' => 'Rancang buket sesuai momen, isi, dan budget yang kamu mau.',
        'custom_action' => 'Request buket custom',
        'featured' => 'Pilihan untukmu',
        'search_results' => 'Hasil pencarian',
        'all_collections' => 'Semua koleksi',
        'found' => 'buket ditemukan',
    ],
    'checkout' => [
        'title' => 'Checkout | Suki Craft', 'back_to_cart' => 'Kembali ke keranjang', 'eyebrow' => 'Satu langkah lagi', 'heading' => 'Atur pengiriman buketmu', 'delivery_data' => 'Data pengiriman', 'confirmation' => 'Konfirmasi', 'recipient_title' => 'Penerima buket', 'recipient_intro' => 'Kami memakai data ini untuk mengatur pengantaran pesananmu.', 'recipient_name' => 'Nama penerima', 'recipient_name_placeholder' => 'Nama lengkap penerima', 'whatsapp' => 'Nomor WhatsApp', 'phone_hint' => 'Gunakan format 08xx atau +628xx.', 'optional' => 'opsional', 'email_placeholder' => 'email@contoh.com', 'delivery_title' => 'Jadwal pengiriman', 'delivery_intro' => 'Pilih tanggal serta waktu yang paling nyaman untuk penerima.', 'delivery_date' => 'Tanggal pengiriman', 'delivery_date_hint' => 'Pesanan dapat dikirim mulai hari ini, selama slot waktunya masih tersedia.', 'arrival_time' => 'Estimasi waktu tiba', 'choose_delivery_time' => 'Pilih waktu pengiriman', 'delivery_address' => 'Alamat lengkap pengiriman', 'address_placeholder' => 'Nama jalan, nomor rumah, RT/RW, kelurahan, kecamatan, dan patokan bila ada', 'additional_notes' => 'Catatan tambahan', 'notes_placeholder' => 'Contoh: Tolong hubungi penerima sebelum tiba.', 'order_eyebrow' => 'Pesananmu', 'summary' => 'Ringkasan', 'close' => 'Tutup', 'view_bouquets' => 'Lihat buket', 'custom_bouquet' => 'Custom Bouquet #:number', 'subtotal' => 'Subtotal buket', 'delivery_fee' => 'Biaya pengiriman', 'promo_code' => 'Kode promo', 'apply' => 'Terapkan', 'promo_discount' => 'Potongan promo', 'total' => 'Total pembayaran', 'total_formula' => 'Total = subtotal buket + biaya pengiriman − potongan promo.', 'submit' => 'Buat pesanan', 'payment_note' => 'Detail pembayaran akan ditampilkan setelah pesanan dibuat.', 'promo_failed' => 'Kode promo tidak dapat diterapkan. Silakan coba lagi.', 'promo_network_failed' => 'Kode promo tidak dapat diterapkan. Muat ulang halaman lalu coba kembali.',
    ],
    'how_to_order' => [
        'title' => 'Cara Pesan | Sukicraft.id', 'description' => 'Panduan mudah memesan buket Sukicraft.id, dari memilih rangkaian hingga melacak pengiriman.', 'hero_eyebrow' => 'Belanja tanpa bingung', 'hero_heading' => 'Dari pilih buket sampai tiba di tangan penerima.', 'hero_intro' => 'Ikuti enam langkah sederhana ini untuk membuat kejutan yang terasa personal. Anda dapat mulai memilih buket tanpa perlu login.', 'browse' => 'Mulai pilih buket', 'track' => 'Lacak pesanan', 'journey' => 'Ringkasan perjalanan pesanan',
        'summary_steps' => [['number' => '01', 'label' => 'Pilih buket'], ['number' => '02', 'label' => 'Tambahkan sentuhan personal'], ['number' => '03', 'label' => 'Periksa keranjang'], ['number' => '04', 'label' => 'Atur pengiriman'], ['number' => '05', 'label' => 'Bayar dan unggah bukti'], ['number' => '06', 'label' => 'Lacak hingga sampai']],
        'steps_eyebrow' => 'Enam langkah mudah', 'steps_heading' => 'Satu per satu, sampai kejutan Anda terkirim.', 'steps_intro' => 'Setiap tahap dirancang agar Anda tetap tahu apa yang perlu dilakukan berikutnya.',
        'steps' => [['number' => '01', 'title' => 'Temukan buket yang tepat', 'description' => 'Buka katalog, lalu pilih rangkaian yang paling sesuai dengan momen dan perasaan yang ingin Anda sampaikan.', 'action' => 'Jelajahi koleksi', 'route' => 'products.index', 'icon' => '✿'], ['number' => '02', 'title' => 'Buat buket lebih personal', 'description' => 'Pilih varian yang tersedia, tulis pesan kartu ucapan, tambahkan catatan untuk florist, lalu tentukan jumlah buket.', 'action' => null, 'route' => null, 'icon' => '♡'], ['number' => '03', 'title' => 'Simpan ke keranjang', 'description' => 'Tekan tombol tambah ke keranjang. Di sana, Anda dapat meninjau kembali detail buket, jumlah, dan subtotal pesanan.', 'action' => 'Buka keranjang', 'route' => 'cart.index', 'icon' => '⌑'], ['number' => '04', 'title' => 'Isi detail pengiriman', 'description' => 'Lanjutkan ke checkout untuk memasukkan nama penerima, WhatsApp, alamat lengkap, tanggal, serta slot waktu pengiriman.', 'action' => 'Lihat katalog', 'route' => 'products.index', 'icon' => '⌖'], ['number' => '05', 'title' => 'Buat pesanan dan bayar', 'description' => 'Setelah pesanan dibuat, lakukan pembayaran melalui QRIS atau transfer bank, kemudian unggah bukti pembayaran untuk diverifikasi.', 'action' => null, 'route' => null, 'icon' => '✓'], ['number' => '06', 'title' => 'Pantau perjalanan pesanan', 'description' => 'Gunakan menu Lacak Pesanan untuk melihat pembaruan status, dari verifikasi pembayaran hingga buket diterima.', 'action' => 'Lacak pesanan', 'route' => 'tracking.create', 'icon' => '⌁']],
        'before_checkout' => 'Sebelum checkout', 'details_heading' => 'Siapkan detail kecil agar pengiriman terasa tepat.', 'details_intro' => 'Semakin lengkap informasi yang Anda berikan, semakin mudah tim kami menyiapkan rangkaian dan kurir mengantarkannya.', 'details' => [['title' => 'Alamat lengkap', 'description' => 'Sertakan nomor rumah, area, dan patokan yang memudahkan kurir.'], ['title' => 'Nomor WhatsApp aktif', 'description' => 'Gunakan nomor yang dapat dihubungi jika kurir membutuhkan konfirmasi.'], ['title' => 'Jadwal pengiriman', 'description' => 'Pilih tanggal serta slot waktu yang sesuai dengan rencana penerima.'], ['title' => 'Pesan kartu & catatan', 'description' => 'Cek kembali ejaan pesan dan tuliskan kebutuhan khusus bila ada.']],
        'faq_eyebrow' => 'Pertanyaan umum', 'faq_heading' => 'Yang perlu Anda tahu sebelum memesan.', 'faqs' => [['question' => 'Apakah saya perlu membuat akun untuk memesan?', 'answer' => 'Tidak. Anda dapat memilih buket, mengisi detail penerima, dan membuat pesanan sebagai tamu. Akun pelanggan dapat digunakan bila Anda ingin mengelola profil dan riwayat pesanan.'], ['question' => 'Kapan saya membayar pesanan?', 'answer' => 'Pembayaran dilakukan setelah pesanan dibuat. Halaman konfirmasi akan menampilkan QRIS atau informasi transfer bank, lalu Anda dapat mengunggah bukti pembayaran.'], ['question' => 'Bagaimana cara mengetahui status pesanan?', 'answer' => 'Buka menu Lacak Pesanan untuk melihat perkembangan pesanan setelah pembayaran dikonfirmasi dan pengiriman dijadwalkan.']],
        'cta_eyebrow' => 'Siap membuat kejutan?', 'cta_heading' => 'Pilih buket yang paling mewakili cerita Anda.', 'cta_action' => 'Lihat koleksi buket',
    ],
];
