@extends('layouts.admin')

@section('title', 'Profil Saya')
@section('page-title', 'Profil Saya')

@section('content')
    <div class="max-w-4xl"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rose-500">Akun admin</p><h1 class="mt-2 font-serif text-3xl font-semibold tracking-tight text-stone-800">Profil & keamanan</h1><p class="mt-2 text-sm text-stone-500">Perbarui informasi akun dan password Anda.</p></div>
        <div class="mt-7 grid gap-6 lg:grid-cols-2"><x-card><h2 class="font-serif text-xl font-semibold text-stone-800">Informasi profil</h2><p class="mt-1 text-sm text-stone-500">Informasi ini digunakan untuk identitas tim.</p><form method="POST" action="{{ route('admin.profile.update') }}" class="mt-6 space-y-5">@csrf @method('PUT')<div><label for="name" class="text-sm font-semibold text-stone-700">Nama</label><input id="name" name="name" value="{{ old('name', $admin->name) }}" required class="mt-2 block h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">@error('name')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="email" class="text-sm font-semibold text-stone-700">Email</label><input id="email" name="email" type="email" value="{{ old('email', $admin->email) }}" required class="mt-2 block h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">@error('email')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><button type="submit" class="h-11 rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white transition hover:bg-rose-600">Simpan perubahan</button></form></x-card>
            <x-card><h2 class="font-serif text-xl font-semibold text-stone-800">Ganti password</h2><p class="mt-1 text-sm text-stone-500">Gunakan password lama untuk mengonfirmasi perubahan.</p><form method="POST" action="{{ route('admin.profile.password.update') }}" class="mt-6 space-y-5">@csrf @method('PUT')<div><label for="current_password" class="text-sm font-semibold text-stone-700">Password saat ini</label><input id="current_password" name="current_password" type="password" required autocomplete="current-password" class="mt-2 block h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">@error('current_password')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="password" class="text-sm font-semibold text-stone-700">Password baru</label><input id="password" name="password" type="password" required autocomplete="new-password" class="mt-2 block h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200">@error('password')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="password_confirmation" class="text-sm font-semibold text-stone-700">Konfirmasi password baru</label><input id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password" class="mt-2 block h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200"></div><button type="submit" class="h-11 rounded-xl border border-rose-200 bg-rose-50 px-5 text-sm font-semibold text-rose-700 transition hover:bg-rose-100">Perbarui password</button></form></x-card></div>
    </div>
@endsection
