@extends('layouts.admin')

@section('title', 'Promosi')
@section('page-title', 'Promosi')

@section('content')
    <div class="flex items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rose-500">Penjualan</p><h1 class="mt-2 font-serif text-3xl font-semibold text-stone-800">Kode promo</h1></div><a href="{{ route('admin.promotions.create') }}" class="rounded-xl bg-rose-500 px-5 py-3 text-sm font-semibold text-white">+ Tambah promo</a></div>
    <div class="mt-6"><x-data-table :headers="['Kode', 'Nilai', 'Masa berlaku', 'Kuota', 'Status', 'Aksi']" :is-empty="$promotions->isEmpty()" empty-title="Belum ada promo" empty-description="Tambahkan kode diskon pertama Anda.">@foreach($promotions as $promotion)<tr><td class="px-5 py-4 font-semibold text-stone-700">{{ $promotion->code }}</td><td class="px-5 py-4 text-sm">{{ $promotion->type === 'percentage' ? $promotion->value.'%' : 'Rp'.number_format($promotion->value, 0, ',', '.') }}</td><td class="px-5 py-4 text-xs text-stone-500">{{ $promotion->starts_at->format('d M Y H:i') }}<br>{{ $promotion->expires_at->format('d M Y H:i') }}</td><td class="px-5 py-4 text-sm">{{ $promotion->usages_count }}/{{ $promotion->usage_limit ?? '∞' }}</td><td class="px-5 py-4"><x-status-badge :status="$promotion->is_active ? 'Aktif' : 'Nonaktif'" /></td><td class="px-5 py-4"><a href="{{ route('admin.promotions.show', $promotion) }}" class="text-xs font-semibold text-rose-600">Statistik</a> <a href="{{ route('admin.promotions.edit', $promotion) }}" class="ml-2 text-xs font-semibold text-rose-600">Edit</a><form method="POST" action="{{ route('admin.promotions.toggle', $promotion) }}" class="inline">@csrf @method('PATCH')<button class="ml-2 text-xs text-stone-500">{{ $promotion->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></td></tr>@endforeach</x-data-table></div><div class="mt-5">{{ $promotions->links() }}</div>
@endsection
