@php($selectedCategoryId = old('custom_bouquet_category_id', $customBouquetCategories->firstWhere('slug', $selectedCategorySlug)?->id))

<section class="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
    <a href="{{ route('products.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-stone-500 transition hover:text-rose-600">← Back to collections</a>
    <div class="mt-7 max-w-3xl"><p class="text-xs font-bold uppercase tracking-[0.2em] text-rose-500">Custom Bouquet Request</p><h1 class="mt-3 font-serif text-4xl font-semibold tracking-tight text-stone-800 sm:text-5xl">Bring your bouquet idea to life</h1><p class="mt-4 text-base leading-7 text-stone-600">Choose a bouquet type and describe the contents and concept. Our florist will send a quote before you continue to payment.</p></div>

    @auth('customer')
        <form method="POST" action="{{ route('custom-requests.store') }}" enctype="multipart/form-data" x-data="{ items: @js(old('items', [['name' => '', 'quantity' => 1, 'notes' => '']])), addItem() { if (this.items.length < 10) this.items.push({ name: '', quantity: 1, notes: '' }); }, removeItem(index) { if (this.items.length > 1) this.items.splice(index, 1); } }" class="mt-8 space-y-6">@csrf
            @if ($errors->any())<div class="rounded-2xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">Please review the highlighted request details.</div>@endif
            <section class="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="font-serif text-2xl font-semibold text-stone-800">Bouquet type and contents</h2><div class="mt-5"><label for="custom_bouquet_category_id" class="text-sm font-semibold text-stone-700">Bouquet category</label><select id="custom_bouquet_category_id" name="custom_bouquet_category_id" required class="mt-2 h-12 w-full rounded-xl border-stone-200 bg-white px-4 text-sm focus:border-rose-300 focus:ring-rose-200"><option value="">Choose a bouquet type</option>@foreach ($customBouquetCategories as $category)<option value="{{ $category->id }}" @selected((string) $selectedCategoryId === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>@error('custom_bouquet_category_id')<p class="mt-2 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror</div>
                <div class="mt-6 flex items-start justify-between gap-4"><div><h3 class="text-sm font-semibold text-stone-700">Your preferred bouquet contents</h3><p class="mt-1 text-sm leading-6 text-stone-500">Add flowers, snacks, cash, plush toys, or anything else you would like arranged.</p></div><button type="button" @click="addItem" :disabled="items.length >= 10" class="shrink-0 rounded-xl bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-600 disabled:opacity-50">+ Add item</button></div>
                <div class="mt-5 space-y-3"><template x-for="(item, index) in items" :key="index"><div class="rounded-2xl border border-stone-100 bg-stone-50 p-4"><div class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_7rem_auto]"><div><label class="text-xs font-semibold text-stone-600">Item name</label><input :name="`items[${index}][name]`" x-model="item.name" required maxlength="255" class="mt-1.5 h-11 w-full rounded-xl border-stone-200 bg-white px-3 text-sm" placeholder="For example: Kinder chocolate"></div><div><label class="text-xs font-semibold text-stone-600">Quantity</label><input :name="`items[${index}][quantity]`" x-model="item.quantity" required min="1" max="99" type="number" inputmode="numeric" class="mt-1.5 h-11 w-full rounded-xl border-stone-200 bg-white px-3 text-sm"></div><button type="button" @click="removeItem(index)" :disabled="items.length === 1" class="self-end rounded-xl px-3 py-2.5 text-sm font-semibold text-rose-600 hover:bg-rose-100 disabled:text-stone-300">Remove</button></div><div class="mt-3"><label class="text-xs font-semibold text-stone-600">Item notes <span class="font-normal text-stone-400">(optional)</span></label><textarea :name="`items[${index}][notes]`" x-model="item.notes" rows="2" maxlength="1000" class="mt-1.5 w-full rounded-xl border-stone-200 bg-white px-3 py-2 text-sm" placeholder="For example: pastel blue"></textarea></div></div></template></div>
            </section>
            <section class="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="font-serif text-2xl font-semibold text-stone-800">Arrangement preferences</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><p class="text-sm font-semibold text-stone-700">Budget range</p><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach (\App\Services\CustomRequestService::budgetRanges() as $value => $range)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-stone-200 px-3 py-3 text-sm text-stone-700"><input type="radio" name="budget_range" value="{{ $value }}" @checked(old('budget_range') === $value) required class="border-stone-300 text-rose-500 focus:ring-rose-300"><span>{{ $range['label'] }}</span></label>@endforeach</div>@error('budget_range')<p class="mt-2 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label for="wrapping_preference" class="text-sm font-semibold text-stone-700">Wrapping preference <span class="font-normal text-stone-400">(optional)</span></label><input id="wrapping_preference" name="wrapping_preference" value="{{ old('wrapping_preference') }}" maxlength="255" class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm" placeholder="For example: white, pink, elegant"></div><div><label for="needed_date" class="text-sm font-semibold text-stone-700">Needed by</label><input id="needed_date" name="needed_date" type="date" min="{{ now('Asia/Jakarta')->toDateString() }}" value="{{ old('needed_date') }}" required class="mt-2 h-12 w-full rounded-xl border-stone-200 px-4 text-sm">@error('needed_date')<p class="mt-2 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror</div>
                <div class="sm:col-span-2"><p class="text-sm font-semibold text-stone-700">Who will provide the items?</p><div class="mt-3 grid gap-2 sm:grid-cols-2"><label class="flex cursor-pointer items-center gap-3 rounded-xl border border-stone-200 px-3 py-3 text-sm text-stone-700"><input type="radio" name="item_source" value="sukicraft_purchases" @checked(old('item_source', 'sukicraft_purchases') === 'sukicraft_purchases') class="border-stone-300 text-rose-500 focus:ring-rose-300"><span>Suki Craft will purchase them</span></label><label class="flex cursor-pointer items-center gap-3 rounded-xl border border-stone-200 px-3 py-3 text-sm text-stone-700"><input type="radio" name="item_source" value="customer_provides" @checked(old('item_source') === 'customer_provides') class="border-stone-300 text-rose-500 focus:ring-rose-300"><span>I will provide them</span></label></div>@error('item_source')<p class="mt-2 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror</div>
                <div class="sm:col-span-2"><label for="additional_notes" class="text-sm font-semibold text-stone-700">Additional notes <span class="font-normal text-stone-400">(optional)</span></label><textarea id="additional_notes" name="additional_notes" rows="4" maxlength="1000" class="mt-2 w-full rounded-xl border-stone-200 px-4 py-3 text-sm" placeholder="For example: colour palette, size, or special occasion">{{ old('additional_notes') }}</textarea></div><div class="sm:col-span-2"><label for="reference_image" class="text-sm font-semibold text-stone-700">Reference image <span class="font-normal text-stone-400">(optional)</span></label><input id="reference_image" name="reference_image" type="file" accept=".jpg,.jpeg,.png,.webp" class="mt-2 block w-full rounded-xl border border-dashed border-rose-200 bg-rose-50/50 px-4 py-4 text-sm text-stone-600">@error('reference_image')<p class="mt-2 text-xs font-medium text-rose-600">{{ $message }}</p>@enderror<p class="mt-2 text-xs text-stone-400">JPG, PNG, or WebP; maximum 2 MB.</p></div></div></section>
            <button type="submit" class="inline-flex h-12 w-full items-center justify-center rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white shadow-lg shadow-rose-200 transition hover:bg-rose-600 sm:w-auto">Submit custom bouquet request</button>
        </form>
    @else
        <div class="mt-8 rounded-3xl border border-rose-100 bg-rose-50 p-5"><h2 class="font-serif text-2xl font-semibold text-stone-800">Ready to bring your idea to life?</h2><p class="mt-2 text-sm leading-6 text-stone-600">Sign in or create an account to send a custom bouquet request and receive a quote from our team.</p><a href="{{ route('customer.login') }}" class="mt-5 inline-flex h-11 items-center rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white transition hover:bg-rose-600">Sign in to start customizing</a></div>
    @endauth
</section>
