@extends('layouts.admin')

@section('title', 'Custom Bouquet ' . $customRequest->request_number)
@section('page-title', 'Detail Custom Bouquet')

@section('content')
    <div><a href="{{ route('admin.custom-requests.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-stone-500 transition hover:text-rose-600">← Kembali ke Custom Bouquet</a><div class="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="font-mono text-xs font-bold uppercase tracking-[0.18em] text-rose-500">{{ $customRequest->request_number }}</p><h1 class="mt-2 font-serif text-3xl font-semibold tracking-tight text-stone-800">Custom Bouquet #{{ $customRequest->request_number }}</h1><p class="mt-2 text-sm text-stone-500">Diajukan {{ $customRequest->created_at->locale('id')->translatedFormat('d F Y, H.i') }} WIB.</p></div><span class="inline-flex w-fit rounded-full bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-700">{{ $customRequest->status->label() }}</span></div></div>

    <div class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <div class="space-y-6">
            <x-card padding="p-5 sm:p-7"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Rincian yang diminta</p><p class="mt-2 text-sm font-semibold text-stone-800">{{ $customRequest->custom_category_name ?? $customRequest->customBouquetCategory?->name ?? $customRequest->product->name }}</p><div class="mt-5 divide-y divide-stone-100">@foreach($customRequest->items as $item)<div class="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><p class="font-semibold text-stone-800">{{ $item->item_name }}</p>@if($item->notes)<p class="mt-1 text-sm text-stone-500">{{ $item->notes }}</p>@endif</div><p class="font-semibold text-stone-700">{{ $item->quantity }}×</p></div>@endforeach</div><dl class="mt-6 grid gap-4 border-t border-stone-100 pt-5 text-sm"><div><dt class="text-stone-400">Dibutuhkan</dt><dd class="mt-1 font-semibold text-stone-700">{{ $customRequest->needed_date->locale('id')->translatedFormat('d F Y') }}</dd></div><div><dt class="text-stone-400">Sumber isi</dt><dd class="mt-1 font-semibold text-stone-700">{{ $customRequest->item_source === 'customer_provides' ? 'Pelanggan membawa sendiri' : 'Suki Craft yang belikan' }}</dd></div>@if($customRequest->wrapping_preference)<div><dt class="text-stone-400">Wrapping</dt><dd class="mt-1 font-semibold text-stone-700">{{ $customRequest->wrapping_preference }}</dd></div>@endif
@if($customRequest->additional_notes)<div><dt class="text-stone-400">Catatan</dt><dd class="mt-1 leading-6 text-stone-700">{{ $customRequest->additional_notes }}</dd></div>@endif</dl>@if($referenceImageUrl)<a href="{{ $referenceImageUrl }}" target="_blank" rel="noopener noreferrer" class="mt-5 inline-flex rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-600 hover:bg-rose-50">Lihat foto referensi</a>@endif</x-card>
            <x-card padding="p-5 sm:p-7"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Aktivitas</p><ol class="mt-5 space-y-5">@foreach($customRequest->histories as $history)<li class="border-l-2 border-rose-100 pl-4"><div class="flex flex-wrap items-center gap-2"><p class="text-sm font-semibold text-stone-800">{{ $history->status->label() }}</p><p class="text-xs text-stone-400">{{ $history->created_at->locale('id')->translatedFormat('d M Y, H.i') }} WIB</p></div><p class="mt-1 text-xs text-stone-400">{{ $history->admin?->name ?? $history->customer?->name ?? 'Sistem' }}</p>@if($history->note)<p class="mt-1 text-sm leading-6 text-stone-600">{{ $history->note }}</p>@endif</li>@endforeach</ol></x-card>
        </div>

        <aside class="space-y-6"><x-card padding="p-5"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Pelanggan</p><p class="mt-3 text-sm font-semibold text-stone-800">{{ $customRequest->customer->name }}</p><p class="mt-1 text-sm text-stone-500">{{ $customRequest->customer->phone }}</p><p class="mt-1 text-sm text-stone-500">{{ $customRequest->customer->email }}</p></x-card>
            @if(in_array($customRequest->status, [\App\Enums\CustomRequestStatus::WAITING_REVIEW, \App\Enums\CustomRequestStatus::REVISION_REQUESTED, \App\Enums\CustomRequestStatus::QUOTATION_SENT], true))
                <x-card padding="p-5"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Kirim penawaran</p><form method="POST" action="{{ route('admin.custom-requests.quote', $customRequest) }}" class="mt-4 space-y-4">@csrf @method('PATCH')<div><label class="text-xs font-semibold text-stone-600">Harga Custom Bouquet</label><input name="quoted_price" type="number" min="1" step="1" inputmode="numeric" value="{{ old('quoted_price', $customRequest->quoted_price === null ? null : (int) $customRequest->quoted_price) }}" required class="mt-1 h-11 w-full rounded-xl border-stone-200 px-3 text-sm">@error('quoted_price')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-xs font-semibold text-stone-600">Berlaku sampai</label><input name="quote_expires_at" type="datetime-local" min="{{ now()->addMinute()->format('Y-m-d\TH:i') }}" value="{{ old('quote_expires_at', $customRequest->quote_expires_at?->format('Y-m-d\TH:i')) }}" required class="mt-1 h-11 w-full rounded-xl border-stone-200 px-3 text-sm">@error('quote_expires_at')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><textarea name="quote_note" rows="4" maxlength="1000" class="w-full rounded-xl border-stone-200 px-3 py-2 text-sm" placeholder="Catatan untuk pelanggan">{{ old('quote_note', $customRequest->quote_note) }}</textarea><button type="submit" class="h-11 w-full rounded-xl bg-rose-500 text-sm font-semibold text-white">Kirim penawaran</button></form>@if ($quoteWhatsAppUrl)<a href="{{ $quoteWhatsAppUrl }}" target="_blank" rel="noopener noreferrer" class="mt-3 inline-flex h-11 w-full items-center justify-center rounded-xl bg-emerald-500 px-4 text-sm font-semibold text-white transition hover:bg-emerald-600">Kirim penawaran via WhatsApp</a>@else<p class="mt-3 text-xs leading-5 text-stone-400">Nomor WhatsApp requester belum tersedia.</p>@endif</x-card>
                <x-card padding="p-5"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Tolak permintaan</p><form method="POST" action="{{ route('admin.custom-requests.reject', $customRequest) }}" class="mt-4">@csrf @method('PATCH')<textarea name="reason" rows="4" required maxlength="1000" class="w-full rounded-xl border-stone-200 px-3 py-2 text-sm" placeholder="Jelaskan alasan atau alternatifnya">{{ old('reason') }}</textarea>@error('reason')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror<button type="submit" class="mt-3 h-11 w-full rounded-xl border border-rose-200 bg-white text-sm font-semibold text-rose-600 hover:bg-rose-50">Tolak dengan catatan</button></form></x-card>
            @elseif($customRequest->quoted_price !== null)
                <x-card padding="p-5"><p class="text-xs font-bold uppercase tracking-[0.16em] text-rose-500">Penawaran terakhir</p><p class="mt-3 font-serif text-2xl font-semibold text-stone-800">Rp{{ number_format($customRequest->quoted_price, 0, ',', '.') }}</p>@if($customRequest->quote_note)<p class="mt-2 text-sm leading-6 text-stone-600">{{ $customRequest->quote_note }}</p>@endif</x-card>
            @endif
        </aside>
    </div>
@endsection