@extends('layouts.admin')

@section('title', 'Akun Admin')
@section('page-title', 'Akun Admin')

@section('content')
    <div><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-rose-500">Khusus super admin</p><h1 class="mt-2 font-serif text-3xl font-semibold tracking-tight text-stone-800">Akun tim admin</h1><p class="mt-2 text-sm text-stone-500">Atur akses tim yang mengelola operasional Suki Craft.</p></div><a href="{{ route('admin.accounts.create') }}" class="inline-flex h-11 items-center justify-center rounded-xl bg-rose-500 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-rose-600">+ Tambah akun</a></div>
        <div class="mt-7"><x-data-table :headers="['Admin', 'Role', 'Status', 'Bergabung', 'Aksi']" :is-empty="$admins->isEmpty()" empty-title="Belum ada akun admin" empty-description="Tambahkan akun untuk anggota tim yang membutuhkan akses.">@foreach($admins as $admin)<tr><td class="whitespace-nowrap px-5 py-4"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-rose-100 text-xs font-bold text-rose-600">{{ str($admin->name)->substr(0, 1)->upper() }}</span><span><span class="block font-semibold text-stone-700">{{ $admin->name }}</span><span class="mt-0.5 block text-xs text-stone-400">{{ $admin->email }}</span></span></div></td><td class="whitespace-nowrap px-5 py-4 text-sm">{{ $admin->role->label() }}</td><td class="whitespace-nowrap px-5 py-4"><x-status-badge :status="$admin->is_active ? 'Aktif' : 'Nonaktif'" /></td><td class="whitespace-nowrap px-5 py-4 text-sm text-stone-500">{{ $admin->created_at->locale('id')->translatedFormat('d M Y') }}</td><td class="whitespace-nowrap px-5 py-4"><div class="flex items-center gap-2"><a href="{{ route('admin.accounts.edit', $admin) }}" class="rounded-lg px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50">Edit</a>@if($admin->is_active && !auth('admin')->user()->is($admin))<form method="POST" action="{{ route('admin.accounts.deactivate', $admin) }}">@csrf @method('PATCH')<button type="submit" class="rounded-lg px-3 py-2 text-xs font-semibold text-stone-500 hover:bg-stone-100">Nonaktifkan</button></form>@endif</div></td></tr>@endforeach</x-data-table></div>
    </div>
@endsection
